# Generated by Django 4.2 on 2023-04-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'get_latest_by': 'modified'},
        ),
    ]
